### ISSUE TITLE
Find out why two qa tests are sensitive to regtest fork difficulty reset to 0x207eeeee

### ISSUE THREAD

**Issue by ftrader** [BTCfork/hardfork_prototype_1_mvf-bu#36]
https://github.com/BTCfork/hardfork_prototype_1_mvf-bu/pull/35 added a workaround for two failing tests which are sensitive to interference of the fork since 0x207eeeee reset introduced in c12e3a6 .

It is still unclear why the regtest difficulty reset to 0x207eeeee (chosen specifically to discern the fork activation difficulty) causes these tests to fail, but not others.

Both of these tests use the ComparisonTestFramework.

I'm opening this issue for investigation.

**Comment by marlengit** [comment]
In https://github.com/BTCfork/hardfork_prototype_1_mvf-bu/pull/39 a reset formula is introduced and the reset fix at 0x207eeeee is disabled by comments.

**Comment by ftrader** [comment]
These two tests were also affected similarly on MVF-Core (amongst others), and are part of the investigation here:

https://github.com/BTCfork/hardfork_prototype_1_mvf-core/issues/7

As they use the ComparisonTestFramework like invalidblockrequest.py, it is likely (but not yet confirmed) that the root cause of their failure on the 0x207eeeee reset is the same as described in https://github.com/BTCfork/hardfork_prototype_1_mvf-core/issues/7#issuecomment-263093969 .

Current status is that these tests pass as the default regtest fork height has been set to 999999, outside of the range of these tests.

**Comment by ftrader** [comment]
Closing MVF prototype developments subsequent to release of Bitcoin Cash clients.
