### ISSUE TITLE
difficultyadjinterval in getblock RPC call - not required?

### ISSUE THREAD

**Issue by ftrader** [BTCfork/hardfork_prototype_1_mvf-bu#37]
The requirements only specify this attribute for the getblockchaininfo RPC call, but it seems to be included in getblock too.

Perhaps this was just for debugging.

**Comment by marlengit** [comment]
This is fixed in https://github.com/BTCfork/hardfork_prototype_1_mvf-bu/pull/38.

**Comment by ftrader** [comment]
Thanks, closing this issue.
